export const StudentList = [
    {
        name: "John",
        address: "12th street",
        city: "Kambur",
        country: "India",
        pincode: "34234",
        score: "500",
        id:'1'
    },
    {
        name: "Alice",
        address: "8th avenue",
        city: "Cerulean",
        country: "USA",
        pincode: "12345",
        score: "600",
        id:'2'
    },
    {
        name: "Bob",
        address: "Main road",
        city: "Greenfield",
        country: "Canada",
        pincode: "56789",
        score: "450",
        id:'3'
    },
    {
        name: "Emily",
        address: "Oak street",
        city: "Meadowville",
        country: "Australia",
        pincode: "67890",
        score: "550",
        id:'4'
    },
    {
        name: "David",
        address: "Sunset boulevard",
        city: "Sunshine City",
        country: "New Zealand",
        pincode: "98765",
        score: "700",
        id:'5'
    },
    {
        name: "Sophia",
        address: "Palm avenue",
        city: "Azure Beach",
        country: "Spain",
        pincode: "54321",
        score: "280",
        id:'6'
    },
    {
        name: "Michael",
        address: "Maple lane",
        city: "Woodland",
        country: "Germany",
        pincode: "87654",
        score: "590",
        id:'7'
    },
    {
        name: "Elena",
        address: "Blossom street",
        city: "Springfield",
        country: "France",
        pincode: "13579",
        score: "520",
        id:'8'
    },
    {
        name: "Alex",
        address: "Riverside drive",
        city: "Riverdale",
        country: "Italy",
        pincode: "24680",
        score: "310",
        id:'9'
    },
    {
        name: "Grace",
        address: "Mountain view",
        city: "Majestic Heights",
        country: "Japan",
        pincode: "11223",
        score: "480",
        id:'10'
    },
    {
        id: 11,
        name: "Liam",
        address: "Golden gate",
        city: "Golden Valley",
        country: "Mexico",
        pincode: "998877",
        score: "670",
    },
    {
        id: 12,
        name: "Ava",
        address: "Silver lane",
        city: "Silvertown",
        country: "Argentina",
        pincode: "112233",
        score: "520",
    },
    {
        id: 13,
        name: "Noah",
        address: "Diamond street",
        city: "Diamond City",
        country: "Brazil",
        pincode: "334455",
        score: "590",
    },
    {
        id: 14,
        name: "Mia",
        address: "Ruby road",
        city: "Rubyville",
        country: "Russia",
        pincode: "556677",
        score: "480",
    },
    {
        id: 15,
        name: "Oliver",
        address: "Sapphire avenue",
        city: "Sapphire Town",
        country: "South Africa",
        pincode: "889900",
        score: "600",
    },
    {
        id: 16,
        name: "Emma",
        address: "Emerald lane",
        city: "Emerald City",
        country: "China",
        pincode: "11223344",
        score: "550",
    },
    {
        id: 17,
        name: "Lucas",
        address: "Pearl street",
        city: "Pearlsville",
        country: "South Korea",
        pincode: "55667788",
        score: "700",
    },
    {
        id: 18,
        name: "Aria",
        address: "Topaz road",
        city: "Topazburg",
        country: "Sweden",
        pincode: "33445566",
        score: "490",
    },
    {
        id: 19,
        name: "Ethan",
        address: "Amber avenue",
        city: "Amberfield",
        country: "Norway",
        pincode: "77889900",
        score: "630",
    },
    {
        id: 20,
        name: "Isabella",
        address: "Citrine lane",
        city: "Citrine City",
        country: "Switzerland",
        pincode: "11223344",
        score: "520",
    },
];
